[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

# [font.bold]
# family = "MesloLGS NF"
# style = "Bold"
#
# [font.bold_italic]
# family = "MesloLGS NF"
# style = "Bold Italic"
#
# [font.italic]
# family = "MesloLGS NF Ita"
# style = "Italic"

# [font.normal]
# family = "MesloLGS NF"
# style = "Regular"

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[selection]
save_to_clipboard = true

[window]
padding = { x = 10 , y = 4 }
dynamic_padding = true
opacity = 0.85
