(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-agenda-files
   '("~/Documents/Org/sh_slt.org" "/home/kirkm/Documents/Org/cal.org"
     "/home/kirkm/Projects/SysA/tracking.org"
     "/home/kirkm/Projects/DS/DSD/ds_lab3.org"
     "/home/kirkm/Projects/Loupe/loupe.org"
     "/home/kirkm/Documents/Org/86_dbg.org" "/home/kirkm/Documents/Org/ads.org"
     "/home/kirkm/Documents/Org/arch.org"
     "/home/kirkm/Documents/Org/awesome_config.org"
     "/home/kirkm/Documents/Org/awm_cont.org"
     "/home/kirkm/Documents/Org/awm_rc.org"
     "/home/kirkm/Documents/Org/awm_testing.org"
     "/home/kirkm/Documents/Org/books.org"
     "/home/kirkm/Documents/Org/c_compiler.org"
     "/home/kirkm/Documents/Org/c_control_flow.org"
     "/home/kirkm/Documents/Org/c_functions.org"
     "/home/kirkm/Documents/Org/c_math.org"
     "/home/kirkm/Documents/Org/c_memory.org"
     "/home/kirkm/Documents/Org/c_selection.org"
     "/home/kirkm/Documents/Org/c_strings.org"
     "/home/kirkm/Documents/Org/c_time.org"
     "/home/kirkm/Documents/Org/c_types.org"
     "/home/kirkm/Documents/Org/c_variables.org"
     "/home/kirkm/Documents/Org/cam_iso.org"
     "/home/kirkm/Documents/Org/cpp_algorithms.org"
     "/home/kirkm/Documents/Org/cpp_arithmetic.org"
     "/home/kirkm/Documents/Org/cpp_best_practices.org"
     "/home/kirkm/Documents/Org/cpp_classes.org"
     "/home/kirkm/Documents/Org/cpp_containers.org"
     "/home/kirkm/Documents/Org/cpp_errors.org"
     "/home/kirkm/Documents/Org/cpp_functional.org"
     "/home/kirkm/Documents/Org/cpp_functions.org"
     "/home/kirkm/Documents/Org/cpp_generic_programming.org"
     "/home/kirkm/Documents/Org/cpp_init_assign.org"
     "/home/kirkm/Documents/Org/cpp_iterators.org"
     "/home/kirkm/Documents/Org/cpp_lists.org"
     "/home/kirkm/Documents/Org/cpp_move_semantics.org"
     "/home/kirkm/Documents/Org/cpp_range_view.org"
     "/home/kirkm/Documents/Org/cpp_references.org"
     "/home/kirkm/Documents/Org/cpp_standard-library.org"
     "/home/kirkm/Documents/Org/cpp_std_array.org"
     "/home/kirkm/Documents/Org/cpp_std_barrier.org"
     "/home/kirkm/Documents/Org/cpp_std_cout.org"
     "/home/kirkm/Documents/Org/cpp_std_function.org"
     "/home/kirkm/Documents/Org/cpp_std_map.org"
     "/home/kirkm/Documents/Org/cpp_std_pair.org"
     "/home/kirkm/Documents/Org/cpp_std_stream.org"
     "/home/kirkm/Documents/Org/cpp_std_string.org"
     "/home/kirkm/Documents/Org/cpp_std_vectors.org"
     "/home/kirkm/Documents/Org/cpp_templates.org"
     "/home/kirkm/Documents/Org/cpp_types.org"
     "/home/kirkm/Documents/Org/cpp_utilities.org"
     "/home/kirkm/Documents/Org/cpp_variables.org"
     "/home/kirkm/Documents/Org/cpp_virtual functions.org"
     "/home/kirkm/Documents/Org/data_dependecies.org"
     "/home/kirkm/Documents/Org/definitions.org"
     "/home/kirkm/Documents/Org/definitions2.org"
     "/home/kirkm/Documents/Org/ds.org" "/home/kirkm/Documents/Org/ds_lab.org"
     "/home/kirkm/Documents/Org/emc.org"
     "/home/kirkm/Documents/Org/emc_binds.org"
     "/home/kirkm/Documents/Org/emc_modes.org"
     "/home/kirkm/Documents/Org/eventlite.org"
     "/home/kirkm/Documents/Org/gdb.org"
     "/home/kirkm/Documents/Org/git_submodules.org"
     "/home/kirkm/Documents/Org/gll.org"
     "/home/kirkm/Documents/Org/gp_animations.org"
     "/home/kirkm/Documents/Org/gp_cli.org"
     "/home/kirkm/Documents/Org/gp_constants.org"
     "/home/kirkm/Documents/Org/gp_files.org"
     "/home/kirkm/Documents/Org/gp_output.org"
     "/home/kirkm/Documents/Org/gp_plotting.org"
     "/home/kirkm/Documents/Org/hk_amt.org"
     "/home/kirkm/Documents/Org/hk_arrays.org"
     "/home/kirkm/Documents/Org/hk_contants.org"
     "/home/kirkm/Documents/Org/hk_ctrl.org"
     "/home/kirkm/Documents/Org/hk_defintions.org"
     "/home/kirkm/Documents/Org/hk_func.org"
     "/home/kirkm/Documents/Org/hk_ghci.org"
     "/home/kirkm/Documents/Org/hk_haskell.org"
     "/home/kirkm/Documents/Org/hk_io.org"
     "/home/kirkm/Documents/Org/hk_keywords.org"
     "/home/kirkm/Documents/Org/hk_mod.org"
     "/home/kirkm/Documents/Org/hk_proofs.org"
     "/home/kirkm/Documents/Org/hk_types.org"
     "/home/kirkm/Documents/Org/index.org"
     "/home/kirkm/Documents/Org/investments.org"
     "/home/kirkm/Documents/Org/journal.org"
     "/home/kirkm/Documents/Org/jv_time.org" "/home/kirkm/Documents/Org/kdb.org"
     "/home/kirkm/Documents/Org/learning.org"
     "/home/kirkm/Documents/Org/lnx_Touchpad.org"
     "/home/kirkm/Documents/Org/lnx_Touchscreen.org"
     "/home/kirkm/Documents/Org/lnx_booting.org"
     "/home/kirkm/Documents/Org/lnx_command_line.org"
     "/home/kirkm/Documents/Org/lnx_dashboard.org"
     "/home/kirkm/Documents/Org/lnx_error.org"
     "/home/kirkm/Documents/Org/lnx_fedora_packages.org"
     "/home/kirkm/Documents/Org/lnx_files.org"
     "/home/kirkm/Documents/Org/lnx_filesystem.org"
     "/home/kirkm/Documents/Org/lnx_globbing.org"
     "/home/kirkm/Documents/Org/lnx_info_and_help.org"
     "/home/kirkm/Documents/Org/lnx_package_creation.org"
     "/home/kirkm/Documents/Org/lnx_package_management.org"
     "/home/kirkm/Documents/Org/lnx_piping.org"
     "/home/kirkm/Documents/Org/lnx_processes.org"
     "/home/kirkm/Documents/Org/lnx_regex.org"
     "/home/kirkm/Documents/Org/lnx_rpmmacros.org"
     "/home/kirkm/Documents/Org/lnx_runlevels.org"
     "/home/kirkm/Documents/Org/lnx_services.org"
     "/home/kirkm/Documents/Org/lnx_shortcuts.org"
     "/home/kirkm/Documents/Org/lnx_spec_file.org"
     "/home/kirkm/Documents/Org/lnx_ssh.org"
     "/home/kirkm/Documents/Org/lnx_useful_commands.org"
     "/home/kirkm/Documents/Org/lnx_users_groups.org"
     "/home/kirkm/Documents/Org/lnx_variables.org"
     "/home/kirkm/Documents/Org/lnx_zsh.org"
     "/home/kirkm/Documents/Org/loupe.org" "/home/kirkm/Documents/Org/lua.org"
     "/home/kirkm/Documents/Org/lua_array.org"
     "/home/kirkm/Documents/Org/lua_atm.org"
     "/home/kirkm/Documents/Org/lua_cli.org"
     "/home/kirkm/Documents/Org/lua_ctrl.org"
     "/home/kirkm/Documents/Org/lua_dbg.org"
     "/home/kirkm/Documents/Org/lua_func.org"
     "/home/kirkm/Documents/Org/lua_io.org"
     "/home/kirkm/Documents/Org/lua_mod.org"
     "/home/kirkm/Documents/Org/lua_str.org"
     "/home/kirkm/Documents/Org/lua_struc.org"
     "/home/kirkm/Documents/Org/make.org" "/home/kirkm/Documents/Org/mc.org"
     "/home/kirkm/Documents/Org/mch.org" "/home/kirkm/Documents/Org/misc.org"
     "/home/kirkm/Documents/Org/nix.org"
     "/home/kirkm/Documents/Org/nix_cont.org"
     "/home/kirkm/Documents/Org/nix_lang.org"
     "/home/kirkm/Documents/Org/nix_pkgs.org"
     "/home/kirkm/Documents/Org/ons.org"
     "/home/kirkm/Documents/Org/org_disp.org"
     "/home/kirkm/Documents/Org/oss.org" "/home/kirkm/Documents/Org/plp.org"
     "/home/kirkm/Documents/Org/proj.org" "/home/kirkm/Documents/Org/py_cli.org"
     "/home/kirkm/Documents/Org/py_debugging.org"
     "/home/kirkm/Documents/Org/py_regex.org"
     "/home/kirkm/Documents/Org/py_selection.org"
     "/home/kirkm/Documents/Org/py_venv.org"
     "/home/kirkm/Documents/Org/rpi_Install.org"
     "/home/kirkm/Documents/Org/rpi_Stack.org"
     "/home/kirkm/Documents/Org/rpi_general.org"
     "/home/kirkm/Documents/Org/rpi_install.org"
     "/home/kirkm/Documents/Org/rpi_mqtt.org"
     "/home/kirkm/Documents/Org/rpi_pis.org"
     "/home/kirkm/Documents/Org/rpi_samba.org"
     "/home/kirkm/Documents/Org/rpi_sensors.org"
     "/home/kirkm/Documents/Org/rpi_todo.org"
     "/home/kirkm/Documents/Org/rpi_web.org"
     "/home/kirkm/Documents/Org/rules.org" "/home/kirkm/Documents/Org/sa.org"
     "/home/kirkm/Documents/Org/sh_amt.org"
     "/home/kirkm/Documents/Org/sh_bash.org"
     "/home/kirkm/Documents/Org/sh_constants.org"
     "/home/kirkm/Documents/Org/sh_ctrl.org"
     "/home/kirkm/Documents/Org/sh_ds.org"
     "/home/kirkm/Documents/Org/sh_error.org"
     "/home/kirkm/Documents/Org/sh_io.org"
     "/home/kirkm/Documents/Org/sh_variables.org"
     "/home/kirkm/Documents/Org/sng.org"
     "/home/kirkm/Documents/Org/sng_tech.org"
     "/home/kirkm/Documents/Org/sng_vcs.org"
     "/home/kirkm/Documents/Org/soft_arch.org"
     "/home/kirkm/Documents/Org/swe.org" "/home/kirkm/Documents/Org/testing.org"
     "/home/kirkm/Documents/Org/tips.org"
     "/home/kirkm/Documents/Org/tmux_config.org"
     "/home/kirkm/Documents/Org/type.org" "/home/kirkm/Documents/Org/ul.org"
     "/home/kirkm/Documents/Org/vi_actions.org"
     "/home/kirkm/Documents/Org/vi_code.org"
     "/home/kirkm/Documents/Org/vi_commands.org"
     "/home/kirkm/Documents/Org/vi_config.org"
     "/home/kirkm/Documents/Org/vi_ex.org"
     "/home/kirkm/Documents/Org/vi_motions.org"
     "/home/kirkm/Documents/Org/vi_plugins.org"
     "/home/kirkm/Documents/Org/vi_regex.org"
     "/home/kirkm/Documents/Org/vi_registers.org"
     "/home/kirkm/Documents/Org/vi_usage.org"
     "/home/kirkm/Documents/Org/vi_visual.org"
     "/home/kirkm/Documents/Org/wb.org" "/home/kirkm/Documents/Org/x86.org"
     "/home/kirkm/Documents/Org/x86_addressing.org"
     "/home/kirkm/Documents/Org/x86_ans.org"
     "/home/kirkm/Documents/Org/x86_cli.org"
     "/home/kirkm/Documents/Org/x86_cpu.org"
     "/home/kirkm/Documents/Org/x86_func.org"
     "/home/kirkm/Documents/Org/x86_instructions.org"
     "/home/kirkm/Documents/Org/x86_io.org"
     "/home/kirkm/Documents/Org/x86_kernel.org"
     "/home/kirkm/Documents/Org/x86_memory.org"
     "/home/kirkm/Documents/Org/x86_registers.org"
     "/home/kirkm/Documents/Org/x86_structure.org"
     "/home/kirkm/Documents/Org/x86_vars.org"
     "/home/kirkm/Documents/Org/x86_work.org"))
 '(org-directory "~/Documents/Org")
 '(package-selected-packages
   '(ace-window all-the-icons dashboard emms gnuplot gtk-pomodoro-indicator llm
     lsp-mode nerd-icons org-pomodoro page-break-lines pomodoro projectile
     register-list shrface tldr yasnippet)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(setq! gdb-many-windows t)
