# In case of using Powerlevel10k
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi


# OPTS

CASE_SENSITIVE="true"
# ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# PLUGINS

plugins=(git fzf 1password zoxide vi-mode sudo rust conda-env alias-finder)

# ZSTYLES

zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default

# SOURCING

source $ZSH/oh-my-zsh.sh
source <(fzf --zsh)
. "$HOME/.cargo/env"

# ENVIRONMENT VARIABLES

# export XDG_CURRENT_DESKTOP=Sway
# export WAYLAND_DISPLAY=wayland-0
export CALIBRE_USE_DARK_PALETTE=0
export EDITOR=nvim
export FZF_DEFAULT_OPTS="--tmux center"
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/home/kirkm/.local/share/JetBrains/Toolbox/scripts::/home/kirkm/.dotnet/tools:/home/kirkm/.local/bin"

# ALIASES

alias vi="nvim"
alias entry="vi ~/Uni/Essentials/Diary/$(date -u +%Y-%m-%d.md)"
alias zrc="vi ~/.config/zsh/zshrc"
alias src="source ~/.zshrc"
alias zj="zellij"
alias clear="clear; tput cup $LINES"
alias ls="lsd"
alias uni="vi ~/Uni"
alias update="sudo dnf update && sudo dnf upgrade"
alias rw="/home/kirkm/.local/share/Steam/steamapps/common/RimWorld/RimWorldLinux" 
alias ca="conda activate"
alias ac="conda deactivate"
alias srch="dnf search"
alias install="sudo dnf install"

# FUNCTIONS

# Force use z
# cd(){
#     echo "Time to use z"
#   }
#
# Don't install python packages outside of a conda env
function pip(){
    if [[ -z $CONDA_PREFIX || $CONDA_PREFIX == "/usr" ]]
      then
        echo "do not install python packages outside of or in a base conda env!!"
        return
    else
      command pip $@
    fi
}

# SETTINGS  

set -o vi

# COMMANDS

tput cup $LINES
pokemon-colorscripts -r --no-title
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
if [[ -z $TMUX ]] then
  tmux
fi
eval "$(starship init zsh)"
# lisgd -g "3,RL,swaymsg workspace next" -d /dev/input/by-path/platform-AMDI0010:00-event -r 45 -m 1200 -t 100 &
# lisgd -g "3,LR,swaymsg workspace prev" -d /dev/input/by-path/platform-AMDI0010:00-event -r 45 -m 1200 -t 100 &
# xmodmap ~/.Xmodmap

